name: Deploy New Relic Agent

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEBIAN_FRONTEND: noninteractive
      NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install New Relic Agent
        run: |
          bash ./scripts/install-newrelic.sh

      - name: Configure New Relic Agent
        run: |
          bash ./scripts/configure-newrelic.sh

      - name: Start New Relic Agent
        run: |
          bash ./scripts/start-newrelic.sh
