name: Install New Relic Agent

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install New Relic agent on the runner machine
        run: |
          pip install newrelic-infra
          sudo systemctl start newrelic-infra

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Connect to Azure VM and install New Relic agent
        run: |
          az vm extension set --resource-group ${{ secrets.AZURE_VM_RESOURCE_GROUP }} --vm-name ${{ secrets.AZURE_VM_NAME }} --name CustomScript --publisher Microsoft.Azure.Extensions --version 2.0 --settings '{"script":"pip install newrelic-infra && sudo systemctl start newrelic-infra"}'
          
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_VM_RESOURCE_GROUP: ${{ secrets.AZURE_VM_RESOURCE_GROUP }}
      AZURE_VM_NAME: ${{ secrets.AZURE_VM_NAME }}
