name: Deploy New Relic Agent

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install New Relic Agent
        run: |
          bash ./scripts/install-newrelic.sh
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Configure New Relic Agent
        run: |
          bash ./scripts/configure-newrelic.sh
        env:
          DEBIAN_FRONTEND: noninteractive
        secrets:
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}

      - name: Start New Relic Agent
        run: bash ./scripts/start-newrelic.sh

