name: Deploy New Relic Agent to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get -y install sshpass

    - name: Copy New Relic agent to Azure VM
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} scp path/to/newrelic-agent-linux.tar.gz Sonika@20.2.241.160:~/newrelic-agent-linux.tar.gz
        # Replace "path/to/newrelic-agent-linux.tar.gz" with the actual path of the New Relic agent installer
        # Replace "username" with your Azure VM username
        # Replace "azure-vm-ip" with your Azure VM's public IP address or hostname

    - name: Connect to Azure VM
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh Sonika@20.2.241.160 "cd ~ && tar -zxvf newrelic-agent-linux.tar.gz"

    - name: Install New Relic agent
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh Sonika@20.2.241.160 "sudo bash ~/newrelic-agent-linux/install.sh"
        # You might need to adjust the path to the installer script if it's different

    - name: Start New Relic agent
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh Sonika@20.2.241.160 "sudo systemctl start newrelic-infra"

    - name: Verify New Relic agent status
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} ssh Sonika@20.2.241.160 "sudo systemctl status newrelic-infra"
