name: Install New Relic Agent

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Connect to Azure VM and install New Relic agent
        run: |
          # Download the New Relic Infrastructure agent installer script
          wget https://download.newrelic.com/infrastructure_agent/linux/newrelic-infra-linux-latest.tar.gz
          tar -xvzf newrelic-infra-linux-latest.tar.gz

          # Install the New Relic Infrastructure agent
          sudo bash newrelic-infra-linux-*.sh

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
