name: Install New Relic Agent

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install New Relic agent on the runner machine
        run: |
          pip install newrelic-infra
          sudo systemctl start newrelic-infra

      - name: Connect to Azure VM and install New Relic agent
        run: |
          # Install SSHpass for password-based SSH authentication
          sudo apt-get install -y sshpass

          # Connect to Azure VM and install New Relic agent using SSH password
          sshpass -p ${{ secrets.AZURE_VM_PASSWORD }} ssh ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} "pip install newrelic-infra && sudo systemctl start newrelic-infra"

    env:
      AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
      AZURE_VM_USER: ${{ secrets.AZURE_VM_USER }}
