name: Deploy New Relic Agent to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install New Relic Infrastructure Agent
        run: |
          curl -o newrelic-infra.deb https://download.newrelic.com/infrastructure_agent/linux/apt/pool/main/n/newrelic-infra/newrelic-infra_1.20.0_amd64.deb
          sudo dpkg -i newrelic-infra.deb
          sudo apt-get update
          sudo apt-get install newrelic-infra -y
          sudo systemctl enable newrelic-infra
          sudo systemctl start newrelic-infra
        env:
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
